name: test

on:
  push:
    breanches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest    
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Ensure browsers are installed
      run: pwsh bin/Release/net8.0/playwright.ps1 install --with-deps
    
    - name: Test Solution
      run: dotnet test TestProject1
      
 
