name: test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest    
      
    steps:
    - uses: actions/checkout@v3

    - name: Install powershell   
      run: dotnet tool install --global PowerShell

    - name: Build Solution   
      run: dotnet build TestProject1
    
    - name: Ensure browsers are installed
      run: pwsh TestProject1/bin/Debug/net8.0/playwright.ps1 install
    
    - name: Test Solution
      run: dotnet test TestProject1

    - name: Download Allure Command-line Tool      
      run: |
         # Download the Allure command-line tool
         wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.zip -O allure.zip
         unzip allure.zip -d allure
         
    - name: Generate Allure Report      
      run: |
        # Generate Allure report based on the NUnit XML test results
        ./allure/allure-2.24.0/bin/allure generate TestProject1/bin/Debug/net8.0/allure-results -o allure-report --clean


    - name: Upload Allure Report        
      uses: actions/upload-artifact@v3
      with:
        name: Allure report
        path: ./TestProject1/allure-report

    - name: Deploy Report to Github Pages      
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}       
        publish_dir: ./TestProject1/allure-report
        publish_branch: allure-report
      
 
